FBV/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('app1/',include('app1.urls',namespace='app1')),
    path('app2/',include('app2.urls',namespace='app2'))
]

app1/urls.py
from django.urls import path
from app1 import views

app_name = 'app1'

urlpatterns = [ 

    path('tabu',views.tabu,name='tabu'),
]

app2/urls.py
from django.urls import path
from app2 import views

app_name = 'app2'

urlpatterns = [
    path('sonu',views.sonu,name='sonu')
]

sample/app1/urls.py
from django.urls import path
from app1 import views

app_name = 'app1'

urlpatterns = [ 
    
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

sample/app1/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,'app1/index.html',{'msg':'This is Index Page'})


def tabu(request):
    data = ['tabusha','9','btech','ECE']
    context = {'data':data}
    return render(request,'app1/tabu.html',context)

app2/views.py
from django.shortcuts import render

# Create your views here.


def sonu(request):
    info =['tinku','6','btech','CSE']
    context = {'info':info}
    return render(request,'app2/sonu.html',context)

sample/app1/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,'app1/index.html',{'msg':'This is Index Page'})

templates/app1/index.html
{% extends 'base.html' %}
{% block b1 %}
{% load static %}
    {{msg}}
{% endblock  %}

templates/app1/tabu.html
{% extends 'base.html' %}
{% block b1 %}
{% load static %}
<img width="150" height="200" src="{% static 'images/tabu.jpg' %}" alt="">
    {% for i in data %}
      <h1>{{i}}</h1>
    {% endfor %}
{% endblock %}

templates/app2/sonu.html
{% extends 'base.html' %}
{% block b1 %}
{% load static %}
<img width="150" height="200" src="{% static 'images/sonu.jpg' %}" alt="">
    {% for j in info %}
      <h1>{{j}}</h1>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    <div class="container">
        <div class="sticky-top">
            <h1 class="text-center p-3 mb-2 bg-info text-dark">Django Web Development : SAMPLE</h1>
            <a href="{% url 'app1:tabu' %}">TABU</a>
            <a href="{% url 'app2:sonu' %}">SONU</a>
        </div>
        <div class="c1 text-center">
            {% block b1 %}
            {% endblock %}
        </div>
        <div class="container fixed-bottom">
            <h1 class="text-center p-3 mb-2 bg-info text-dark">Thanks for visiting</h1>
        </div>
    </div>
</body>
</html>